services:
  redis:
    image: "redis:latest"
    command: redis-server
    ports:
      - "16379:6379"
    volumes:
      - ".cache/redis_data:/data"

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '26379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local